id: IBC148677
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:31:41+00:00'
last_modified: '2022-06-08T08:08:13.070237+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2733
  title: ཆོས་རྣམ་ཀུན་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    0F35:
      image_group_id: I1KG2751
      title: ''
      total_pages: 1434
      order: 1
      base_file: 0F35.txt
    774A:
      image_group_id: I1KG2752
      title: ''
      total_pages: 1610
      order: 2
      base_file: 774A.txt
    DD4A:
      image_group_id: I1KG2753
      title: ''
      total_pages: 1308
      order: 3
      base_file: DD4A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
